# Generated by Django 5.2.5 on 2025-12-02 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('texto', models.CharField(max_length=255, verbose_name='Pregunta')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoría')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Pregunta de auditoría',
                'verbose_name_plural': 'Preguntas de auditoría',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('objetivo', models.CharField(blank=True, max_length=200, verbose_name='Objetivo / Alcance')),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada')], default='EN_PROCESO', max_length=20, verbose_name='Estado')),
                ('observaciones_generales', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AuditAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('C', 'Cumple'), ('NC', 'No cumple'), ('NA', 'No aplica')], max_length=2, verbose_name='Respuesta')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='auditoria.audit', verbose_name='Auditoría')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auditoria.auditquestion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de auditoría',
                'verbose_name_plural': 'Respuestas de auditoría',
                'unique_together': {('auditoria', 'pregunta')},
            },
        ),
    ]
