# Generated by Django 5.2.6 on 2025-09-05 19:03

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sitio_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas/')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sitio_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Temática',
                'verbose_name_plural': 'Temáticas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='estudio',
            field=models.ForeignKey(blank=True, help_text='Studio/Developer (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.estudio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, help_text='Xbox, PlayStation, Nintendo, etc.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tematicas',
            field=models.ManyToManyField(blank=True, help_text='Indie, Retro, Pixel Art, etc.', related_name='productos', to='catalogo.tematica'),
        ),
    ]
