# Generated by Django 5.2.6 on 2025-09-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_estudio_marca_tematica_producto_estudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='estudios/banners/'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='estudios/'),
        ),
        migrations.AddField(
            model_name='tematica',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='tematicas/iconos/'),
        ),
    ]
