# Generated by Django 5.2.5 on 2025-09-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_productoimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Aparece en la sección Destacados del home'),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado_orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden en el home (1 arriba)'),
        ),
    ]
