# Generated by Django 5.2.5 on 2025-09-10 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_producto_destacado_producto_destacado_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='segmentos/iconos/')),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='segmento',
            field=models.ForeignKey(blank=True, help_text='Hombres, Mujeres, Niños, Unisex', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.segmento'),
        ),
    ]
