# Generated by Django 5.2.5 on 2025-09-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=191, unique=True),
        ),
    ]
