# Generated by Django 5.2.5 on 2025-12-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_birth_date_profile_city_profile_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rol',
            field=models.CharField(blank=True, choices=[('', 'Sin rol especial'), ('AUDITOR', 'Auditor'), ('ADMIN', 'Administrador')], default='', max_length=20),
        ),
    ]
